name: tests & formatting
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check && cargo clippy --all-features -- -Dwarnings && cargo test --all-features
