name: tests & formatting
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check && cargo clippy --all-features -- -Dwarnings && cargo test --all-features
